pom.xml

Updates the Spring Boot Version to 2.5.14 due to a CVE for one of its sub-dependencies in the previous version (spring-security-config:5.5.6)

update spring boot version to 2.5.4

---

pom.xml

Update the version for spring-cloud-openfeign-core due to the findings in https://avd.aquasec.com/nvd/2021/cve-2021-22044/

update and specify version for spring-cloud-openfeign-core

---

pom.xml

Updating to Spring Version 5.3.20 due to the findings in https://avd.aquasec.com/nvd/2022/cve-2022-22965/

update spring version to 5.3.20

---

backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SparqlQueries.java
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/ModelWithReferenceToTraceability.ttl
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/Traceability.ttl
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/ValidModelForApiTests.ttl

This commit reverts the test models back to BAMM version 1.0.0.

Revert test models back to BAMM version 1.0.0

---

backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/PersistenceLayer.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SparqlQueries.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java
backend/src/main/resources/static/semantic-hub-openapi.yaml
backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java

The changes of this PR add a new endpoint to the Semantic Hub that allows to filter for a list of URNs. Only these model entries will then be returned as part of the request. Pagination is included.

URN filter endpoint

---

README.md
backend/Dockerfile
backend/pom.xml
backend/src/main/java/org/eclipse/tractusx/semantics/OAuthSecurityConfig.java
backend/src/main/resources/application.yml
pom.xml

Update to spring 2.7.3 and cleanup pom

Update spring version

---

pom.xml

Updates snakeyaml dependency to 1.33 due to CVE in previous version (CVE-2022-38752).

Updates snakeyaml dependency to 1.33 due to CVE

---

pom.xml

- increase springboot version to 2.7.5
- increase explicitly spring-security-core version to 5.7.5 to fix cve-2022-31692

Fix cve-2022-31692

---

pom.xml

Increase jackson-databind version to 2.14.0

fix cve-2022-42003 (jackson-databind)

---

pom.xml

* update org.springframework.boot to version 2.7.6
* remove dependency spring-security-core since the version of spring-security-core is updated over the dependency org.springframework.boot

fix CVE-2022-31692 (spring-security-web)

---

.github/workflows/release.yml

Semantic-hub app is built with java 17. Therefore the release.yml needs to be updated to setup Java with version 17.

Adjust github action release.yml File to setup with java 17

---

.github/actions/generate-dependencies-notice/action.yml
.github/actions/generate-dependencies-notice/index.js
.github/actions/generate-dependencies-notice/package-lock.json
.github/actions/generate-dependencies-notice/package.json
backend/Dockerfile

These changes adjust the existing Dockerfile to include a build step for the Semantic Hub. Also it integrates a new action that parses the license info of the used dependencies, including the base image layers.

Adjust Dockerfile to include build step

---

charts/semantic-hub/Chart.yaml

Hello, I would like to suggest adding the license header for the Chart.yaml file to avoid license conflicts and following tractus-x release guidelines: https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
Kind regards
Maximilian Wesener
Traceability-Foss

doc(Chart.yaml): Add license header for trg-5-02

---

backend/src/main/java/org/eclipse/tractusx/semantics/hub/domain/ModelPackageStatus.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java
backend/src/main/resources/static/semantic-hub-openapi.yaml
backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java

This adds a new status standardized. Already released models can be transitioned into the standardized status. It is not possible to delete a standardized model.

Introduce new status standardized

---

.github/workflows/publish-image-semantic-hub.yml
.github/workflows/release.yml

This PR includes the following features:
* Introduce a new Github action for build and publish the sldt-semantic-hub images to dockerhub. 
* Adjust release.yml to trigger the new Github action after creating a new tag.

feat:docker-hub-build-workflow

---

backend/pom.xml
pom.xml

Fixes
Get diagram functionality fixes for SAMM and BAMM models
- Removed duplicate transient guru.nidi dependencies.

fix:excluded guru.nidi libraries from esmf sdk

---

backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java

Commented get model diagram API since this call crashing the server for bugger models.
Fixes
- Get model diagram API returns HTTP status code 501 - Not Implemented

fix:Commented get model diagram call

---

.tractusx

This PR adds an initial version of the `.tractusx` metadata file like described in [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5).
If there are any other repositories, that are connected to the Semantic Hub, that together form a product, please point that out or add the connected repos later on
Fixes #143

chore: add initial version of .tractusx metadata

---

backend/pom.xml
backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelNotFoundException.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/ModelPackageNotFoundException.java
backend/src/main/resources/catena-template.css
backend/src/main/resources/static/semantic-hub-openapi.yaml
charts/chart-testing-config.yaml
pom.xml

Added [License and copyright header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02/#description) information.

feat:License and copyright header information

---

CHANGELOG.md
backend/src/main/resources/static/semantic-hub-openapi.yaml

- Added summary for the open api paths

feat:Added summary for the open api paths

---

CHANGELOG.md
DEPENDENCIES
pom.xml

Veracode CVEs fix in jetty-http jar.
- CVE-2023-36478 | CWE-190
Denial Of Service (DoS): org.eclipse.jetty is vulnerable to Denial Of Service (DoS). The vulnerability arises from the library's failure to appropriately limit the size in HPACK header values. This allows an attacker to repeatedly send maliciously crafted HTTP messages, leading to an integer overflow and ultimately causing an application crash through the `checkSize` function in `MetaDataBuilder.java`.
- CVE-2023-40167| CWE-130
HTTP Request Smuggling: Jetty is vulnerable to HTTP Request Smuggling. The vulnerability is due to accepting `+` character proceeding the content-length in the request. This vulnerability can be exploited by the attacker to possibly conduct request smuggling attacks.

fix:Veracode CVEs fix

---

.github/actions/generate-dependencies-notice/action.yml
.github/actions/generate-dependencies-notice/index.js
.github/workflows/gitleaks.yml
.github/workflows/helm-release.yml
.github/workflows/helm-test.yml
.github/workflows/kics.yml
.github/workflows/publish-image-semantic-hub.yml
.github/workflows/release.yml
.github/workflows/trivy.yml
.github/workflows/veracode.yaml
charts/semantic-hub/Chart.yaml
charts/semantic-hub/templates/graphdb/graphdb-deployment.yaml
charts/semantic-hub/templates/graphdb/graphdb-pvc.yaml
charts/semantic-hub/templates/graphdb/graphdb-service.yaml
charts/semantic-hub/templates/hub/hub-ingress.yaml

Legal information header has been corrected:
- the legal information header will start at line 1 in each class
- double copyright expression like "Copyright (c) 2023 Copyright (c) 2023" have been corrected

legal header information corrected

---

CHANGELOG.md
backend/Dockerfile

fixes https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/191 - Removed the docker apk upgrade and update commands.

fix:TRG 4.02 Using un-altered container base image

---

.github/workflows/helm-test.yml

This change will let the `ct install` step execute for `workflow_dispatch` events.
fixes #193

chore(build): only skip ct install on PRs

---

.github/workflows/helm-test.yml

This PR bumps the default k8s version used for `kindest/node` to a recent one.

chore(build): bump default kind k8s node version

---

.github/workflows/semantic-hub-e2e-test.yml
e2e-tests/requirements.txt
e2e-tests/semantic-hub/common.yaml
e2e-tests/semantic-hub/test_api.tavern.yaml

add automated Tests for semantic-hub

add automated Tests for semantic-hub

---

.github/workflows/build-snapshot.yml
CHANGELOG.md
backend/src/test/java/org/eclipse/tractusx/semantics/FusekiTestContainer.java

Fixed the jena-fuseki-docker version to 4.7.0 for the test case to fix https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/196

fix:Test setup

---

charts/semantic-hub/README.md

A backtick in the helm command leads to an error.

Fix typo in README.md

---

backend/src/main/java/org/eclipse/tractusx/semantics/ApiExceptionHandler.java
backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/ContactInformation-2.0.0.ttl
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/DigitalProductPassport-samm.ttl
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/Pcf-3.0.0.ttl
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/PhysicalDimensions-2.0.0.ttl
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/SerialPartTypization-2.0.0.ttl
backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/TransmissionPass.ttl

Handled  invalid models HTTP 500 error issue.

fix:Fix for invalid models HTTP 500 error issue

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/PersistenceLayer.java
backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java
backend/src/main/resources/static/semantic-hub-openapi.yaml
backend/src/test/java/org/eclipse/tractusx/semantics/hub/AbstractModelsApiTest.java
backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java

Enabled state transitions without modification of models.

feat:Enabled state transitions without modification of models
