eclipse-tractusx/sldt-semantic-hub

- .github/workflow/gitleaks.yml
Signed-off-by: Johannes Kristan <johannes.kristan@bosch.io>
> Add secret scanning to repository

- backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/PersistenceLayer.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SparqlQueries.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java
- backend/src/main/resources/static/semantic-hub-openapi.yaml
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiFilterTest.java
This PR removes the filter functionality in the Semantic Hub to search for specific BAMM elements.
> Deactivate name search

- backend/pom.xml
- pom.xml
Temporary fix for a finding in snakeyaml 1.30
> Adjust snakeyaml version to 1.31

- README.md
- backend/Dockerfile
- backend/deployment/semantic-hub/Chart.yaml
- backend/deployment/semantic-hub/values.yaml
- backend/pom.xml
- backend/src/main/java/org/eclipse/tractusx/semantics/OAuthSecurityConfig.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/PersistenceLayer.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SparqlQueries.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/static/semantic-hub-openapi.yaml
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java
- pom.xml
This PR manually includes the latest changes into main to create a new version.
> Merge main into release

- .github/workflows/kics.yml
This PR integrates a new GH Actions workflow for the KICS scan.
> Add KICS workflow

- backend/deployment/.vscode/settings.json
- backend/src/main/resources/static/semantic-hub-openapi.yaml
This PR fixes the KICS scan findings (errors) that occur because of the missing array maxItems property.
> Fix KICS findings

- .github/workflows/gitleaks.yml
These changes adjust the existing gitleaks workflow to fix a problem with the sarif upload
> Fix gitleaks workflow

- charts/semantic-hub/Chart.yaml
Increase app-version to 0.1.0-M3
Increase chartversion to 0.1.4
> Increase chartversion to 0.1.4 and app-version to 0.1.0-M3

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/values.yaml
Remove access mode ReadWriteMany from pvcAccessModes
> Remove mode ReadWriteMany from pvcAccessModes

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/values.yaml
* enabled embeddedTripleStore as Default
* disabled ingress
> Adjust default configuration

- README.md
This change includes a new section as part of the README that informs about the available container image.
> Adjust README to contain image notice section

- backend/pom.xml
- backend/src/main/java/org/eclipse/tractusx/semantics/ApiExceptionHandler.java
- backend/src/main/java/org/eclipse/tractusx/semantics/LocalOauthSecurityConfig.java
- backend/src/main/java/org/eclipse/tractusx/semantics/OAuthSecurityConfig.java
- backend/src/main/java/org/eclipse/tractusx/semantics/SemanticHubApplication.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/TripleStoreConfiguration.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/TripleStoreProperties.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application.yml
- backend/src/test/java/org/eclipse/tractusx/semantics/ApplicationTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/FusekiTestContainer.java
- backend/src/test/java/org/eclipse/tractusx/semantics/SwaggerUITest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/AbstractModelsApiTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/HealthCheckTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/JwtTokenFactory.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiFilterTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiPaginationTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiSecurityTest.java
- backend/src/test/resources/application-test.yml
- pom.xml
- introduce testcontainer for e2e tests
> Update to Springboot 3

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/templates/hub/hub-deployment.yaml
- charts/semantic-hub/values.yaml
Adjust chart configuration (deployment.yaml and value.yaml):
* Split value for image into image registry, repository and version.
* Introduce appVersion as default
> Making image version configurable and introduce appVersion as default

- charts/semantic-hub/templates/hub/hub-deployment.yaml
- charts/semantic-hub/values.yaml
* adjust queryendpoint and updateendpoint for default values.yml
* Add /ds to baseurl of database graphdb
> * add /ds to baseurl of graphdb (fuseki)

- .github/workflows/release.yml
Remove existing folder ./jena-fuseki.zip before pull new jena-fuseki version
> fix release file- remove existing folder jena-fuseki.zip

- pom.xml
Update json to version 20230227
> fix CVE-2022-45688

- CHANGELOG.md
- charts/semantic-hub/Chart.yaml
Increase chart version to 0.1.12
Increase app version to 0.2.2-M1
> Prepare helm release 0.1.12

- CHANGELOG.md
- charts/semantic-hub/Chart.yaml
increase appversion to 0.2.3-M1
increase helm version to 0.1.14
> Prepare release 0.1.14

- CHANGELOG.md
- charts/semantic-hub/Chart.yaml
Increase helm to version 0.1.15
Increase image to version 0.2.4-M1
> Prepare release 0.1.15

- .github/workflows/veracode-scan.yml
- Add veracode-scan for semantic-hub in eclipse-tractusx repository
> feat:Add veracode-scan github action

- pom.xml
* fix cve-2023-20862-20873
* update dependencies to the newest version
> fix CVE and update dependencies

- .github/workflows/publish-image-semantic-hub.yml
- .github/workflows/release.yml
This PR includes the following features:
Introduce a new Github action for build and publish the sldt-semantic-hub images to dockerhub.
Adjust release.yml to trigger the new Github action after creating a new tag.
> feat:docker-hub-build-workflow

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/values.yaml
* Update app-image to 0.2.7-M1
* Update helm version to 0.1.20
> feat: Prepare release 0.1.20

- CHANGELOG.md
Prepare semantic-hub version to 0.2.8-M1
> Prepare semantic-hub version to 0.2.8-M1

- charts/semantic-hub/Chart.yaml
Prepare helm version 0.1.21 
Increase app version to 0.2.8-M1
> Prepare helm version 0.1.21

- backend/src/test/java/org/eclipse/tractusx/semantics/hub/AbstractModelsApiTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/TestUtils.java
- backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/DependentModel-bamm.ttl
- backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/ModelDependency-bamm.ttl
- backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/ModelWithReferenceToTraceability-bamm.ttl
- backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/Traceability-bamm.ttl
- backend/src/test/resources/org/eclipse/tractusx/semantics/hub/persistence/models/ValidModelForApiTests-bamm.ttl
Add test cases for BAMM models
Fixes
- Add test cases for BAMM models
> fix:Added BAMM tests

- CHANGELOG.md
Added BAMM and SAMM Support
Fixes
- Added BAMM and SAMM Support
> fix:Added BAMM and SAMM Support

- charts/semantic-hub/Chart.yaml
Updated helm chart with new release version 0.1.22.
> feat:updated helm Chart.yaml

- DEPENDENCIES
> Update DEPENDENCIES file

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- Fix CVE-2023-34035 (update springboot to version 3.1.2)
- Fix CVE-2023-2976 (update google guava to version 32.1.1-jre)
> fix: CVE-2023-34035 and CVE-2023-2976

- backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SparqlQueries.java
Supports loading existing BAMM models.
Fixes
- Changed the auxiliary name space to load BAMM models.
> fix:BAMM existing data loading issue

- .tractusx
.tractusx file added to repository
> .tractusx file added

- CHANGELOG.md
Added 0.2.10-M1 release details.
> doc:Added 0.2.10-M1 release details

- charts/semantic-hub/Chart.yaml
Updated helm chart with new release version 0.1.23
> feat:Updated helm chart with new release version 0.1.23

- INSTALL.md
- README.md
- docs/documentation.md
INSTALL.md file added to Semantic Hub
> add INSTALL.md

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/values.yaml
The resource management settings in values.yaml has been adjusted.
> Resource management settings adjusted

- .github/workflows/helm-test.yml
- charts/chart-testing-config.yaml
- charts/semantic-hub/Chart.yaml
Helm test cases improved.
Build Image step is removed, which was not used during test.
Added node_image variable
added license to chart-testing-config.yaml
> Bug: Improved Helm test

- DEPENDENCIES
Updated the dependencies using dash-licenses tool.
> feat:Updated the dependencies

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/values.yaml
Improved value for the cpu request in the values.yml
> Improved value for cpu request

- INSTALL.md
- README.md
- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/values.yaml
Added documentation to build fuseki docker image and updated Helm values.xml.
> feat:Added fuseki documentation

- .github/workflows/trivy.yml
Improvements in Trivy scan:
1) Modified the image ref to 'latest'
2) Removed the unnecessary build image step because we test 'latest' image
> Feat: Improved Trivy scan

- CHANGELOG.md
Updating CHANGELOG.md file with new version
> Feat: Updating CHANGELOG.md file

- charts/semantic-hub/Chart.yaml
updating app version to 0.2.11-M1 and helm version to 0.1.28
> Feat: updating app and helm version

- CHANGELOG.md
- DEPENDENCIES
- backend/pom.xml
- pom.xml
- Veracode Third-Party Components vulnerability fix for CVE-2022-44729| CWE-918
> feat:Veracode Third-Party Components vulnerability fix

- charts/semantic-hub/Chart.yaml
Updated helm version to 0.1.30 and image version to 0.2.12
> prepare-release-0.1.30

- CHANGELOG.md
- Corrected the changelog with correction version
> Corrected the CHANGELOG.md

- charts/semantic-hub/Chart.yaml
Updated helm version to 0.1.31 and image version to 0.2.14
> Prepare release 0.1.31

- CHANGELOG.md
- backend/src/main/java/org/eclipse/tractusx/semantics/ApiExceptionHandler.java
- backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java
> fix:Handle UrnSyntaxException

- SECURITY.md
> apply updated SECURITY.md

- .github/workflows/helm-test.yml
Included Helm test workflow update changes https://github.com/eclipse-tractusx/sldt-discovery-finder/pull/67/files in helm upgrade.
> fix:Helm test workflow update changes

- docs/documentation.md
Just for clarification - do you have one backend?
Your security assessment in confluence shows two processes / backends.
> docs: add data flow diagram from security assessment

- .github/workflows/release.yml
fix release YML to use fuseki build image version 4.7.0
> fix release YML to use fuseki build image version 4.7.0

- charts/semantic-hub/Chart.yaml
Updated helm version to 0.1.33 and image version to 0.2.15
> Prepare release 0.1.33

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
fixes found findings for CVE-2023-34053, CVE-2023-6378
> fixes findings for CVE-2023-34053, CVE-2023-6378

- charts/semantic-hub/Chart.yaml
Prepare helm version 0.1.34 and imageversion 0.2.16
> Prepare helm version 0.1.34 and imageversion 0.2.16

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/templates/hub/hub-secret.yaml
- charts/semantic-hub/values.yaml
Adjust to implement autogenerate Password if not set
> Adjust to implement autogenerate Password if not set

- DEPENDENCIES
- backend/pom.xml
- pom.xml
Update springboot version to 3.2.2
> Update springboot version to 3.2.2

- CHANGELOG.md
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/SDKAccessHelper.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java
- backend/src/main/resources/static/semantic-hub-openapi.yaml
Generate Diagrams with SVG Format
> Generate Diagrams with SVG Format

- .github/workflows/publish-image-semantic-hub.yml
- DOCKER_NOTICE.md
- README.md
Separate notice file for docker
> Separate notice file for docker

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
Update Springboot to version 3.2.3
> Update Springboot to version 3.2.3

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/templates/_helpers.tpl
- charts/semantic-hub/templates/graphdb/graphdb-deployment.yaml
- charts/semantic-hub/templates/graphdb/graphdb-pvc.yaml
- charts/semantic-hub/templates/graphdb/graphdb-service.yaml
- charts/semantic-hub/templates/hub/hub-deployment.yaml
- charts/semantic-hub/templates/hub/hub-ingress.yaml
- charts/semantic-hub/templates/hub/hub-secret.yaml
- charts/semantic-hub/templates/hub/hub-service.yaml
- charts/semantic-hub/templates/keycloak/init-script-configmap.yaml
- charts/semantic-hub/values.yaml
> improve helm chart

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/templates/graphdb/graphdb-deployment.yaml
- charts/semantic-hub/templates/graphdb/graphdb-pvc.yaml
> Fix helm- pvc name

- CHANGELOG.md
> Prepare stabil version 0.3.1

- charts/semantic-hub/Chart.yaml
> Prepare helm release 0.2.1

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/templates/hub/hub-deployment.yaml
- charts/semantic-hub/values.yaml
Make livenessProbe and readinessProbe configurable
> Make livenessProbe and readinessProbe configurable

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
> Fix: Security scan fixes

- charts/semantic-hub/Chart.yaml
Helm release 0.2.3
App version 0.3.2
> Feat: Helm release 0.2.3

- .github/workflows/trivy.yml
> Fix Trivy scan

- CHANGELOG.md
- backend/src/main/resources/application.yml
- pom.xml
> Fix: High security fix

- .github/workflows/trivy.yml
> Fix:Fixed trivy file typo

- charts/semantic-hub/Chart.yaml
> Prep: Prepare helm release 0.3.0

- .github/codeql/codeql-config.yaml
- .github/workflows/codeql.yml
Add custom configuration file for codeql
- Exclude tests from scanning to optimize pipeline runs
- Exclude warning and recommandations to have focused reports
- Exclude:  java/spring-disabled-csrf-protection check as this application is backend and disabling csrf is intended. 
This API is exclusively used by non-browser clients. 
> chore: add code ql configuration

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/README.md
- charts/semantic-hub/templates/hub/hub-deployment.yaml
> add Trg 0.4.7 read only file

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/README.md
Replaced catenax-ng reference with catenax-ev
closes #291
> Bug:Replaced catenax-ng reference with catenax-ev

- .github/workflows/build-snapshot.yml
- CHANGELOG.md
- pom.xml
Fix security issues (update dependencies)
> Fix security issues (update dependencies)

- CHANGELOG.md
- pom.xml
Exclude exlcude com.google.protobuf lib  because of CVE https://avd.aquasec.com/nvd/2024/cve-2024-7254
> Exclude exlcude com.google.protobuf lib

- CHANGELOG.md
- pom.xml
Update velocity-engine-core to version 2.4
> Update velocity-engine-core to version 2.4

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
> Chore/prepare release 0.5.0

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
Update Springboot to 3.2.5
Updated Spring security 6.3.4
> Fix: Fixed security issues

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/README.md
> Prepare helm release 0.4.1

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/README.md
Helm release 0.4.2. 
App version 0.5.2
> Prep: Helm release 0.4.2

- .github/workflows/semantic-hub-e2e-test.yml
> Fix: Upload artifact version

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/README.md
> Prep: Helm release 0.4.4

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
> Fix: fixed cve spring-webmvc

- charts/semantic-hub/Chart.yaml
- charts/semantic-hub/README.md
prepare helm release 0.5.0, appVersion 0.6.0
> Prep: prepare helm release 0.5.0
